service: sfwrapup-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  stage: dev
  region: ap-southeast-2


functions:
  app: 
    handler: app/app.handler 
    events:
      - http: 
          path: /
          method: ANY
          cors: true      
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
